spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/deviceauthorizer
    username: radarcns
    password: radarcns
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

device-clients:
  device-auth-configs:
    - device_type: FitBit
      authorization_endpoint: https://www.fitbit.com/oauth2/authorize
      token_endpoint: https://api.fitbit.com/oauth2/token
      client_id:
      client_secret:
      scope: activity heartrate location nutrition sleep social weight profile settings
    - deviceType: something else
      authorizationEndpoint:
      tokenEndpoint:
      clientId:
      clientSecret:
      scope: