version: '2'
services:
    radar-auth-app:
        image: auth-test:latest
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-postgresql:5432/deviceauthorizer
            - SPRING_DATASOURCE_USERNAME=radarcns
            - SPRING_DATASOURCE_PASSWORD=radarcns
            - DEVICE_AUTH
            - APP_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
        volumes:
            - ./etc:/app-includes
    auth-postgresql:
        image: postgres:9.6.2
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_USER=radarcns
          - POSTGRES_PASSWORD=radarcns
          - POSTGRES_DB=deviceauthorizer
